# Generated by Django 2.0.6 on 2020-10-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authordetail',
            table='t_author_detail',
        ),
    ]
